name: Build Mac Executable

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4  # Actualiza a la versión v4

    - name: Set up Python
      uses: actions/setup-python@v4  # Actualiza a la versión v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executable
      run: |
        pyinstaller --onefile --name=VictorCODE optimizando.py

    - name: Upload Executable
      uses: actions/upload-artifact@v4  # Actualiza a la versión v4
      with:
        name: VictorCODE
        path: dist/VictorCODE

